import { createFileRoute } from "@tanstack/react-router"
import { useQuery, useQueryClient } from "@tanstack/react-query"
import { useForm } from "@tanstack/react-form"
import { useEffect, useRef, useState } from "react"
import { toast } from "sonner"
import { Button } from "@workspace/ui/components/button"
import { Input } from "@workspace/ui/components/input"
import { Skeleton } from "@workspace/ui/components/skeleton"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@workspace/ui/components/dialog"
import { Workspace } from "../components/workspace"
import { loadIdentity } from "../auth/route-access"
import { requireRole } from "../auth/policy"
import { createVaultEntry, deleteVaultEntry, listVault, listVaultAccess, reauthenticateVault, revealVaultSecret, rewrapVaultKeys, updateVaultEntry } from "../features/vault/vault.functions"
import { vaultMetadata } from "../features/vault/validation"

export const Route = createFileRoute("/vault")({ beforeLoad: async () => { const identity = await loadIdentity(); requireRole(identity.user.role, "editor"); return identity }, component: VaultPage })
type Entry = Awaited<ReturnType<typeof listVault>>["entries"][number]
function VaultPage() {
  const { user } = Route.useRouteContext(), cache = useQueryClient()
  const query = useQuery({ queryKey: ["vault-metadata"], queryFn: () => listVault() })
  const [editing, setEditing] = useState<Entry | "new" | null>(null), [deleting, setDeleting] = useState<Entry | null>(null), [busy, setBusy] = useState(false)
  async function refresh() { await cache.invalidateQueries({ queryKey: ["vault-metadata"] }); await cache.invalidateQueries({ queryKey: ["vault-access"] }) }
  async function run(action: () => Promise<unknown>) { setBusy(true); try { await action(); await refresh(); toast.success("Vault updated") } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to update vault.") } finally { setBusy(false) } }
  return <Workspace name={user.name} role={user.role}><div className="mb-5 flex justify-between"><h1 className="font-heading text-3xl font-semibold">Password vault</h1>{user.role === "admin" && <Button onClick={() => setEditing("new")}>New entry</Button>}</div>
    <p className="mb-4 rounded border bg-muted p-3 text-sm">All access to this vault is logged.</p>
    {query.data?.ephemeralDevelopment && <p role="status" className="mb-4 rounded border border-amber-500 p-3 text-sm">Development vault: the encryption key exists only in server memory. Restarting or reloading the server makes existing secrets unreadable. Use disposable test credentials.</p>}
    <PasswordConfirmation onConfirmed={refresh} required={query.data?.needsReauthentication ?? false} />
    {query.isPending ? <Skeleton className="h-64" /> : query.isError ? <p role="alert">Unable to load the vault.</p> : <div className="overflow-x-auto rounded border bg-card"><table className="w-full text-left text-sm"><thead className="border-b"><tr>{["Label", "Username", "Category", "Last rotated", "Created by", "Actions"].map((label) => <th className="p-3" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y">{query.data.entries.map((entry) => <tr key={entry.id}><td className="p-3 font-medium">{entry.url ? <a href={entry.url} rel="noreferrer" target="_blank" className="underline">{entry.label}</a> : entry.label}</td><td className="p-3">{entry.username}</td><td className="p-3">{entry.category}</td><td className="p-3">{entry.lastRotatedAt ? new Date(entry.lastRotatedAt).toLocaleDateString() : "—"}</td><td className="p-3">{entry.createdBy}</td><td className="p-3"><SecretActions id={entry.id} onAccess={refresh} />{user.role === "admin" && <div className="mt-1 flex gap-1"><Button size="sm" variant="ghost" onClick={() => setEditing(entry)}>Edit</Button><Button size="sm" variant="ghost" onClick={() => setDeleting(entry)}>Delete</Button></div>}</td></tr>)}</tbody></table>{!query.data.entries.length && <p className="p-6 text-sm">No vault entries yet — an administrator can add the first credential.</p>}</div>}
    {user.role === "admin" && <><AccessLog /><Button className="mt-4" variant="outline" disabled={busy} onClick={() => void run(async () => { const result = await rewrapVaultKeys(); toast.success(`${result.changed} keys rewrapped${result.more ? "; run again for remaining entries" : ""}`) })}>Rewrap entries with current master key</Button></>}
    <Dialog open={editing !== null} onOpenChange={(open) => { if (!open) setEditing(null) }}><DialogContent><DialogHeader><DialogTitle>{editing === "new" ? "New vault entry" : "Edit vault entry"}</DialogTitle><DialogDescription>Confirm your password first if your session is older than 15 minutes.</DialogDescription></DialogHeader>{editing && <VaultForm entry={editing === "new" ? undefined : editing} onSaved={async () => { setEditing(null); await refresh() }} />}</DialogContent></Dialog>
    <Dialog open={Boolean(deleting)} onOpenChange={(open) => { if (!open) setDeleting(null) }}><DialogContent><DialogHeader><DialogTitle>Delete {deleting?.label}?</DialogTitle><DialogDescription>The encrypted secret will be erased. Its access history remains for auditing.</DialogDescription></DialogHeader><Button disabled={busy} variant="destructive" onClick={() => void run(async () => { if (deleting) await deleteVaultEntry({ data: { id: deleting.id } }); setDeleting(null) })}>Delete entry</Button></DialogContent></Dialog>
  </Workspace>
}
function PasswordConfirmation({ required, onConfirmed }: { required: boolean; onConfirmed: () => Promise<void> }) {
  const input = useRef<HTMLInputElement>(null), [busy, setBusy] = useState(false)
  return <form className="mb-5 flex flex-wrap items-center gap-2" onSubmit={async (event) => { event.preventDefault(); if (!input.current) return; const password = input.current.value; input.current.value = ""; setBusy(true); try { await reauthenticateVault({ data: { password } }); await onConfirmed(); toast.success("Password confirmed for 15 minutes") } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to confirm password.") } finally { setBusy(false) } }}><label className="text-sm" htmlFor="vault-password">{required ? "Confirm password to access secrets" : "Renew password confirmation"}</label><Input ref={input} id="vault-password" type="password" autoComplete="current-password" required maxLength={256} className="w-60" /><Button disabled={busy} variant="outline">Confirm</Button></form>
}
function SecretActions({ id, onAccess }: { id: string; onAccess: () => Promise<void> }) {
  // Plaintext remains only in this component's local state, never props/loaders/query caches.
  const [secret, setSecret] = useState<string | null>(null), [busy, setBusy] = useState(false)
  const generation = useRef(0)
  useEffect(() => { const clear = () => { generation.current++; setSecret(null) }; window.addEventListener("blur", clear); document.addEventListener("visibilitychange", clear); return () => { generation.current++; window.removeEventListener("blur", clear); document.removeEventListener("visibilitychange", clear) } }, [])
  useEffect(() => { if (secret === null) return; const timer = window.setTimeout(() => setSecret(null), 30000); return () => window.clearTimeout(timer) }, [secret])
  async function access(action: "reveal" | "copy") { setSecret(null); setBusy(true); const request = ++generation.current; try { const response = await revealVaultSecret({ data: { id, action } }); if (!response.ok) throw new Error("Unable to access secret."); const value = await response.text(); if (request !== generation.current || document.hidden) return; if (action === "copy") { await navigator.clipboard.writeText(value); toast.success("Copied to clipboard") } else setSecret(value); await onAccess() } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to access secret.") } finally { setBusy(false) } }
  return <div><div className="flex gap-1"><Button size="sm" variant="outline" disabled={busy} onClick={() => secret === null ? void access("reveal") : setSecret(null)}>{secret === null ? "Reveal" : "Hide"}</Button><Button size="sm" variant="outline" disabled={busy} onClick={() => void access("copy")}>Copy</Button></div>{secret !== null && <div className="mt-2 max-w-64 break-all rounded border p-2 font-mono text-xs">{secret}<p className="mt-1 font-sans text-muted-foreground">Hides after 30 seconds</p></div>}</div>
}
function VaultForm({ entry, onSaved }: { entry?: Entry; onSaved: () => Promise<void> }) {
  const secret = useRef<HTMLInputElement>(null)
  const form = useForm({ defaultValues: { label: entry?.label ?? "", username: entry?.username ?? "", category: entry?.category ?? "", url: entry?.url ?? "" }, validators: { onSubmit: vaultMetadata }, onSubmit: async ({ value }) => { const plaintext = secret.current?.value ?? ""; if (secret.current) secret.current.value = ""; try { if (entry) await updateVaultEntry({ data: { ...value, id: entry.id, secret: plaintext || undefined } }); else await createVaultEntry({ data: { ...value, secret: plaintext } }); await onSaved(); toast.success("Vault entry saved") } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to save entry.") } } })
  return <form className="space-y-3" onSubmit={(event) => { event.preventDefault(); void form.handleSubmit() }}>{(["label", "username", "category", "url"] as const).map((name) => <form.Field key={name} name={name}>{(field) => <label className="block text-sm capitalize">{name}<Input required={name === "label"} type={name === "url" ? "url" : "text"} value={field.state.value} onChange={(event) => field.handleChange(event.target.value)} /><span className="text-xs text-destructive">{field.state.meta.errors.map((error) => error?.message).join(", ")}</span></label>}</form.Field>)}<label className="block text-sm">{entry ? "New secret (leave blank to keep current)" : "Secret"}<Input ref={secret} type="password" autoComplete="new-password" required={!entry} maxLength={4096} /></label><form.Subscribe selector={(state) => state.isSubmitting}>{(busy) => <Button disabled={busy}>Save entry</Button>}</form.Subscribe></form>
}
function AccessLog() {
  const [page, setPage] = useState(0)
  const query = useQuery({ queryKey: ["vault-access", page], queryFn: () => listVaultAccess({ data: { page } }) })
  return <section className="mt-8"><h2 className="mb-3 text-xl font-semibold">Access log</h2>{query.isPending ? <Skeleton className="h-32" /> : query.isError ? <p role="alert">Unable to load access log.</p> : <div className="overflow-auto rounded border"><table className="w-full text-left text-xs"><thead><tr>{["Time", "Actor", "Action", "Entry", "IP", "User agent"].map((title) => <th key={title} className="p-2">{title}</th>)}</tr></thead><tbody>{query.data.map((row) => <tr key={row.id} className="border-t"><td className="p-2">{new Date(row.createdAt).toLocaleString()}</td><td className="p-2">{row.actor}</td><td className="p-2">{row.action}</td><td className="p-2">{row.entryId}</td><td className="p-2">{row.ipAddress}</td><td className="max-w-64 truncate p-2" title={row.userAgent ?? ""}>{row.userAgent}</td></tr>)}</tbody></table></div>}<div className="mt-2 flex gap-2"><Button size="sm" variant="outline" disabled={page === 0} onClick={() => setPage(page - 1)}>Previous</Button><Button size="sm" variant="outline" disabled={!query.data || query.data.length < 50} onClick={() => setPage(page + 1)}>Next</Button></div></section>
}
