import { createFileRoute, Link } from "@tanstack/react-router"
import { useQuery, useQueryClient } from "@tanstack/react-query"
import { useForm } from "@tanstack/react-form"
import { useState } from "react"
import { toast } from "sonner"
import { Button } from "@workspace/ui/components/button"
import { Input } from "@workspace/ui/components/input"
import { Skeleton } from "@workspace/ui/components/skeleton"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@workspace/ui/components/dialog"
import { Workspace } from "../../components/workspace"
import { loadIdentity } from "../../auth/route-access"
import { getAdminAccess } from "../../auth/session.functions"
import { roleSchema } from "../../auth/policy"
import { changeManagedRole, createManagedUser, listManagedUsers, resetManagedPassword, setManagedBan } from "../../features/admin/users.functions"
import { managedUserInput } from "../../features/admin/validation"
import type { z } from "zod"

export const Route = createFileRoute("/admin/users")({ beforeLoad: async () => { const identity = await loadIdentity(); await getAdminAccess(); return identity }, component: UsersPage })
function UsersPage() {
  const { user } = Route.useRouteContext(), cache = useQueryClient()
  const [creating, setCreating] = useState(false), [busy, setBusy] = useState(false), [resetTarget, setResetTarget] = useState<{ id: string; name: string } | null>(null)
  const query = useQuery({ queryKey: ["managed-users"], queryFn: () => listManagedUsers() })
  async function run(action: () => Promise<unknown>) { setBusy(true); try { await action(); await cache.invalidateQueries({ queryKey: ["managed-users"] }); toast.success("Account updated") } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to update account.") } finally { await cache.invalidateQueries({ queryKey: ["managed-users"] }); setBusy(false) } }
  return <Workspace name={user.name} role={user.role}><div className="mb-6 flex justify-between"><div><h1 className="font-heading text-3xl font-semibold">User accounts</h1><p className="mt-2 text-sm text-muted-foreground">Invite team members and manage access. All changes are logged.</p></div><Button onClick={() => setCreating(true)}>Invite user</Button></div>
    {query.isPending ? <Skeleton className="h-64" /> : query.isError ? <p role="alert">Unable to load accounts.</p> : <div className="overflow-x-auto rounded-lg border bg-card"><table className="w-full text-left text-sm"><thead className="border-b bg-muted/40"><tr>{["User", "Role", "Status", "Last sign-in", "Email delivery", "Actions"].map((label) => <th key={label} className="p-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y">{query.data.map((account) => <tr key={account.id}><td className="p-3"><p className="font-medium">{account.name}</p><p className="text-xs text-muted-foreground">{account.email}</p></td><td className="p-3"><select aria-label={`Role for ${account.name}`} className="rounded border bg-background p-1" value={account.role} disabled={busy || account.id === user.id} onChange={(event) => { const role = roleSchema.parse(event.target.value); void run(() => changeManagedRole({ data: { userId: account.id, role } })) }}>{roleSchema.options.map((role) => <option key={role}>{role}</option>)}</select></td><td className="p-3">{account.banned ? "Banned" : "Active"}</td><td className="p-3 text-xs">{account.lastSignInAt ? new Date(account.lastSignInAt).toLocaleString() : "Never"}</td><td className="p-3 text-xs">{account.emailDeliveryStatus ?? "No email sent"}</td><td className="p-3"><div className="flex gap-1"><Button variant="ghost" size="sm" disabled={busy || account.id === user.id} onClick={() => void run(() => setManagedBan({ data: { userId: account.id, banned: !account.banned, reason: "Suspended by administrator" } }))}>{account.banned ? "Unban" : "Ban"}</Button><Button variant="ghost" size="sm" disabled={busy || account.id === user.id} onClick={() => setResetTarget(account)}>Force reset</Button></div></td></tr>)}</tbody></table></div>}
    <p className="mt-4 text-xs text-muted-foreground">For your own password, use <Link to="/forgot-password" className="text-primary underline">password reset</Link>. Failed invitations can be resent with Force reset.</p>
    <Dialog open={creating} onOpenChange={setCreating}><DialogContent><DialogHeader><DialogTitle>Invite a team member</DialogTitle><DialogDescription>We create the account and email a single-use password setup link valid for 24 hours.</DialogDescription></DialogHeader><InviteForm onSaved={async () => { setCreating(false); await cache.invalidateQueries({ queryKey: ["managed-users"] }) }} /></DialogContent></Dialog>
    <Dialog open={Boolean(resetTarget)} onOpenChange={(open) => { if (!open) setResetTarget(null) }}><DialogContent><DialogHeader><DialogTitle>Force password reset for {resetTarget?.name}?</DialogTitle><DialogDescription>This immediately revokes sessions and replaces the existing password. A setup link valid for one hour will be emailed. If delivery fails, retry from this page.</DialogDescription></DialogHeader><Button disabled={busy} onClick={() => { if (!resetTarget) return; void run(async () => { const result = await resetManagedPassword({ data: { userId: resetTarget.id } }); setResetTarget(null); if (!result.emailSent) throw new Error("Password reset enforced, but email delivery failed. Retry sending.") }) }}>Revoke access and send reset</Button></DialogContent></Dialog>
  </Workspace>
}
function InviteForm({ onSaved }: { onSaved: () => Promise<void> }) {
  const defaultValues: z.input<typeof managedUserInput> = { name: "", email: "", role: "viewer" }
  const form = useForm({ defaultValues, validators: { onSubmit: managedUserInput }, onSubmit: async ({ value }) => { try { const result = await createManagedUser({ data: value }); await onSaved(); if (result.emailSent) toast.success("Account created and invitation sent"); else toast.error("Account created, but invitation delivery failed. Use Force reset to retry.") } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to create account.") } } })
  return <form className="space-y-3" onSubmit={(event) => { event.preventDefault(); void form.handleSubmit() }}><form.Field name="name">{(field) => <Input aria-label="Full name" placeholder="Full name" required value={field.state.value} onChange={(event) => field.handleChange(event.target.value)} />}</form.Field><form.Field name="email">{(field) => <Input aria-label="Email address" placeholder="Email address" type="email" required value={field.state.value} onChange={(event) => field.handleChange(event.target.value)} />}</form.Field><form.Field name="role">{(field) => <select className="w-full rounded border bg-background p-2" aria-label="Role" value={field.state.value} onChange={(event) => field.handleChange(roleSchema.parse(event.target.value))}>{roleSchema.options.map((role) => <option key={role}>{role}</option>)}</select>}</form.Field><form.Subscribe selector={(state) => state.isSubmitting}>{(submitting) => <Button disabled={submitting}>Create account and invite</Button>}</form.Subscribe></form>
}
